name: Scheduled Task
on: push
  # schedule:
  #   - cron: '*/1 * * * *'
jobs:
  task-output:
    runs-on: ubuntu-latest
    name: A Server time printing job
    steps:
      - name: Echo current time
        run: echo "The current server-time is $(date)"
    
