name: manual-event-trigger

on:
    workflow_dispatch:
        inputs:
            names:
                description: 'Name of the person to greet'
                required: true
                type: string
            greeting:
                description: 'Type of greeting'
                required: true
                type: string
            data:
                description: 'Base64 encoded content of file'
                required: false
                type: string

jobs:
    manual-input-event:
        runs-on: ubuntu-latest
        steps:
            - name: Decode File Content
              run: | 
                echo "${{ inputs.data }}" | base64 --decode > ./decoded_file.txt
            - name: Display Greeting
              run: |
                echo "${{ inputs.greeting }}, ${{ inputs.names }}!"
            - name: Display File Content
              run: | 
                echo "Contents of the File are as follow: "
                cat ./decoded_file.txt
