name: Scheduled Task
on:
  schedule:
    - cron: '* * * * *'
jobs:
  task_output:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "The current server-time is $(date)"
    


        